# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapTest
  pod 'Mapbox-iOS-SDK', '~> 5.4'

end
